### ISSUE TITLE
.gaul list is not parsed by Tigger

### ISSUE THREAD

**Issue by sihle20** [ratt-ru/tigger-lsm#41]
I was trying to load   ``` /home/gcilitshana/Project/New/madroon-1/im3-MFS-image.gaul ``` and I got this error:

```
### running match_catalogs
# invoking callable catalog_utils.match_catalogs() using external interpreter
# Loading im3-MFS-image.srl: PyBDSM .gaul/.srl file
# loaded 8306 sources from 'main' im3-MFS-image.srl
# Loading im3-MFS-image.gaul: PyBDSM .gaul/.srl file
# Traceback (most recent call last):
#   File "<string>", line 17, in <module>
#   File "/home/gcilitshana/Project/New/madroon-1/catalog_utils.py", line 38, in match_catalogs
#     model = Tigger.load(catalog)
#   File "/home/gcilitshana/venv4/lib/python3.8/site-packages/Tigger/Models/Formats/__init__.py", line 126, in
load
#     return import_func(filename)
#   File "/home/gcilitshana/venv4/lib/python3.8/site-packages/Tigger/Models/Formats/PyBDSMGaul.py", line 88, in
load
#     raise ValueError("this .gaul file does not appear to contain a format string")
# ValueError: this .gaul file does not appear to contain a format string
```

**Comment by o-smirnov** [comment]
@sihle20 could you please attach the actual file to the issue, in case it goes missing in your filesystem.

**Comment by o-smirnov** [comment]
Can't upload ``.gaul`` directly, but you can fool it by adding a .txt suffix:

[im3-MFS-image.gaul.txt](https://github.com/ratt-ru/tigger-lsm/files/10849981/im3-MFS-image.gaul.txt)

**Comment by o-smirnov** [comment]
Hang on, I think this is an .srl file that has been renamed into .gaul? Obligatory Python reference: https://montypython.fandom.com/wiki/Fish_Licence

(Might be my fault -- I didn't commit my omstimelation changes which you need for the new pipeline...)

**Comment by sihle20** [comment]
I've  updated omstimelation on my side and re-ran the source-catalog step but still get the same error from .gaul list. 

No I didn't rename .srl into .gaul :)

**Comment by o-smirnov** [comment]
Can you post the log from your source-catalog step?

**Comment by sihle20** [comment]
Here is the log file:

[im3-MFS-image.fits.pybdsf.log](https://github.com/ratt-ru/tigger-lsm/files/10880258/im3-MFS-image.fits.pybdsf.log)

**Comment by IanHeywood** [comment]
Just a general comment: `thresh_pix           = 4.0` in a 10k x 10k image will probably result in a lot of false detections.

**Comment by sihle20** [comment]
Okay Noted.
